# Generated by Django 3.2.16 on 2023-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_plan_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='full_price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Full_price_with_discount'),
        ),
    ]
