# Generated by Django 3.2.16 on 2023-07-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Comment'),
        ),
    ]
