# Generated by Django 3.2.16 on 2023-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client', 'plan', 'service'], name='services_su_client__5285d8_idx'),
        ),
    ]
