# Generated by Django 3.2.16 on 2023-07-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_subscription_services_su_client__5285d8_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='services_su_client__5285d8_idx',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client_id', 'plan_id', 'service_id'], name='services_su_client__5285d8_idx'),
        ),
    ]
